swagger: "2.0"
info:
  version: "0.0.1"
  title: Surprise API
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of the responses to the client (Accepts)
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /surprise:
    x-swagger-router-controller: surprise
    post:
      description: Gather data from different public APIs and return data
      operationId: fetch
      parameters:
        - name: body
          in: body
          required: false
          schema:
            type: object
            $ref: "#/definitions/InputData"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DataFetchResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  InputData:
    type: object
  DataFetchResponse:
    type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
